const Food =[
        {
            name:"Avocado Oil",
            type:"Oil",
            amount:100,
            calories:884,
            protein:0,
            carbs:0,
            fat:100
        },
        {
            name:"Butter",
            type:"Oil",
            amount:100,
            calories:717,
            protein:0,
            carbs:0,
            fat:81
        },
        {
            name:"Canola Oil",
            type:"Oil",
            amount:100,
            calories:884,
            protein:0,
            carbs:0,
            fat:100
        },
        {
            name:"Coconut Oil",
            type:"Oil",
            amount:100,
            calories:862,
            protein:0,
            carbs:0,
            fat:100
        },
        {
            name:"Grapeseed Oil",
            type:"Oil",
            amount:100,
            calories:884,
            protein:0,
            carbs:0,
            fat:100
        },
        {
            name:"Olive Oil",
            type:"Oil",
            amount:100,
            calories:884,
            protein:0,
            carbs:0,
            fat:100
        },
        {
            name:"Walnut Oil",
            type:"Oil",
            amount:100,
            calories:884,
            protein:0,
            carbs:0,
            fat:100
        },
        {
            name:"Apple",
            type:"Fruit",
            amount:100,
            calories:52,
            protein:0,
            carbs:13,
            fat:0
        },
        {
            name:"Apricot",
            type:"Fruit",
            amount:100,
            calories:48,
            protein:1,
            carbs:11,
            fat:0
        },
        {
            name:"Avocado",
            type:"Fruit",
            amount:100,
            calories:160,
            protein:2,
            carbs:8,
            fat:14
        },
        {
            name:"Acai",
            type:"Fruit",
            amount:100,
            calories:80,
            protein:2,
            carbs:4,
            fat:6
        },
        {
            name:"Banana",
            type:"Fruit",
            amount:100,
            calories:89,
            protein:1,
            carbs:22,
            fat:0
        },
        {
            name:"Blueberry",
            type:"Fruit",
            amount:100,
            calories:57,
            protein:0,
            carbs:14,
            fat:0
        },
        {
            name:"Blood Orange",
            type:"Fruit",
            amount:100,
            calories:47,
            protein:0,
            carbs:11,
            fat:0
        },
        {
            name:"Cantaloupe",
            type:"Fruit",
            amount:100,
            calories:34,
            protein:0,
            carbs:8,
            fat:0
        },
        {
            name:"Cranberry",
            type:"Fruit",
            amount:100,
            calories:46,
            protein:0,
            carbs:12,
            fat:0
        },
        {
            name:"Cherry",
            type:"Fruit",
            amount:100,
            calories:63,
            protein:1,
            carbs:16,
            fat:0
        },
        {
            name:"Cucumber",
            type:"Fruit",
            amount:100,
            calories:15,
            protein:0,
            carbs:3,
            fat:0
        },
        {
            name:"Date",
            type:"Fruit",
            amount:100,
            calories:277,
            protein:1,
            carbs:74,
            fat:0
        },
        {
            name:"Durian",
            type:"Fruit",
            amount:100,
            calories:147,
            protein:1,
            carbs:27,
            fat:5
        },
        {
            name:"Elderberry",
            type:"Fruit",
            amount:100,
            calories:73,
            protein:0,
            carbs:18,
            fat:0
        },
        {
            name:"Grapefruit",
            type:"Fruit",
            amount:100,
            calories:33,
            protein:0,
            carbs:8,
            fat:0
        },
        {
            name:"Grapes",
            type:"Fruit",
            amount:100,
            calories:69,
            protein:0,
            carbs:18,
            fat:0
        },
        {
            name:"Guava",
            type:"Fruit",
            amount:100,
            calories:68,
            protein:2,
            carbs:14,
            fat:0
        },
        {
            name:"Honeydew",
            type:"Fruit",
            amount:100,
            calories:36,
            protein:0,
            carbs:9,
            fat:0
        },
        {
            name:"Jackfruit",
            type:"Fruit",
            amount:100,
            calories:95,
            protein:1,
            carbs:23,
            fat:0
        },
        {
            name:"Kiwi",
            type:"Fruit",
            amount:100,
            calories:61,
            protein:1,
            carbs:14,
            fat:0
        },
        {
            name:"Kumquat",
            type:"Fruit",
            amount:100,
            calories:71,
            protein:1,
            carbs:15,
            fat:0
        },
        {
            name:"Lemon",
            type:"Fruit",
            amount:100,
            calories:29,
            protein:1,
            carbs:9,
            fat:0
        },
        {
            name:"Lime",
            type:"Fruit",
            amount:100,
            calories:30,
            protein:0,
            carbs:10,
            fat:0
        },
        {
            name:"Lingonberry",
            type:"Fruit",
            amount:100,
            calories:50,
            protein:1,
            carbs:12,
            fat:0
        },
        {
            name:"Loganberry",
            type:"Fruit",
            amount:100,
            calories:55,
            protein:1,
            carbs:13,
            fat:0
        },
        {
            name:"Loquat",
            type:"Fruit",
            amount:100,
            calories:47,
            protein:0,
            carbs:12,
            fat:0
        },
        {
            name:"Lychee",
            type:"Fruit",
            amount:100,
            calories:66,
            protein:0,
            carbs:16,
            fat:0
        },
        {
            name:"Mango",
            type:"Fruit",
            amount:100,
            calories:60,
            protein:0,
            carbs:14,
            fat:0
        },
        {
            name:"Nectarine",
            type:"Fruit",
            amount:100,
            calories:44,
            protein:1,
            carbs:10,
            fat:0
        },
        {
            name:"Orange",
            type:"Fruit",
            amount:100,
            calories:47,
            protein:0,
            carbs:11,
            fat:0
        },
        {
            name:"Papaya",
            type:"Fruit",
            amount:100,
            calories:43,
            protein:0,
            carbs:10,
            fat:0
        },
        {
            name:"Passion Fruit",
            type:"Fruit",
            amount:100,
            calories:97,
            protein:2,
            carbs:23,
            fat:0
        },
        {
            name:"Peach",
            type:"Fruit",
            amount:100,
            calories:39,
            protein:0,
            carbs:9,
            fat:0
        },
        {
            name:"Pear",
            type:"Fruit",
            amount:100,
            calories:57,
            protein:0,
            carbs:15,
            fat:0
        },
        {
            name:"Persimmon",
            type:"Fruit",
            amount:100,
            calories:127,
            protein:0,
            carbs:33,
            fat:0
        },
        {
            name:"Pineapple",
            type:"Fruit",
            amount:100,
            calories:50,
            protein:0,
            carbs:13,
            fat:0
        },
        {
            name:"Plum",
            type:"Fruit",
            amount:100,
            calories:46,
            protein:0,
            carbs:11,
            fat:0
        },
        {
            name:"Pomegranate",
            type:"Fruit",
            amount:100,
            calories:83,
            protein:1,
            carbs:18,
            fat:1
        },
        {
            name:"Raspberry",
            type:"Fruit",
            amount:100,
            calories:52,
            protein:1,
            carbs:11,
            fat:0
        },
        {
            name:"Star Fruit",
            type:"Fruit",
            amount:100,
            calories:31,
            protein:1,
            carbs:6,
            fat:0
        },
        {
            name:"Strawberry",
            type:"Fruit",
            amount:100,
            calories:32,
            protein:0,
            carbs:7,
            fat:0
        },
        {
            name:"Tamarind",
            type:"Fruit",
            amount:100,
            calories:239,
            protein:2,
            carbs:62,
            fat:0
        },
        {
            name:"Tangelo",
            type:"Fruit",
            amount:100,
            calories:53,
            protein:0,
            carbs:13,
            fat:0
        },
        {
            name:"Tangerine",
            type:"Fruit",
            amount:100,
            calories:53,
            protein:0,
            carbs:13,
            fat:0
        },
        {
            name:"Watermelon",
            type:"Fruit",
            amount:100,
            calories:30,
            protein:0,
            carbs:7,
            fat:0
        },
        {
            name:"Yuzu",
            type:"Fruit",
            amount:100,
            calories:29,
            protein:1,
            carbs:9,
            fat:0
        },
        {
            name:"Acorn Squash",
            type:"Vegetable",
            amount:100,
            calories:103,
            protein:0,
            carbs:16,
            fat:4
        },
        {
            name:"Arrowroot",
            type:"Vegetable",
            amount:100,
            calories:65,
            protein:4,
            carbs:13,
            fat:0
        },
        {
            name:"Artichoke",
            type:"Vegetable",
            amount:100,
            calories:209,
            protein:2,
            carbs:9,
            fat:0
        },
        {
            name:"Arugula",
            type:"Vegetable",
            amount:100,
            calories:25,
            protein:2,
            carbs:3,
            fat:0
        },
        {
            name:"Asparagus",
            type:"Vegetable",
            amount:100,
            calories:20,
            protein:2,
            carbs:3,
            fat:0
        },
        {
            name:"Beet",
            type:"Vegetable",
            amount:100,
            calories:43,
            protein:1,
            carbs:9,
            fat:0
        },
        {
            name:"Beetroot",
            type:"Vegetable",
            amount:100,
            calories:43,
            protein:1,
            carbs:9,
            fat:0
        },
        {
            name:"Bell Peppers",
            type:"Vegetable",
            amount:100,
            calories:31,
            protein:0,
            carbs:6,
            fat:0
        },
        {
            name:"Black Eyed Pea",
            type:"Vegetable",
            amount:100,
            calories:90,
            protein:2,
            carbs:18,
            fat:0
        },
        {
            name:"Bok Choy",
            type:"Vegetable",
            amount:100,
            calories:16,
            protein:1,
            carbs:3,
            fat:0
        },
        {
            name:"Broccoli",
            type:"Vegetable",
            amount:100,
            calories:34,
            protein:2,
            carbs:6,
            fat:0
        },
        {
            name:"Brussel Sprouts",
            type:"Vegetable",
            amount:100,
            calories:43,
            protein:3,
            carbs:8,
            fat:0
        },
        {
            name:"Butternut Squash",
            type:"Vegetable",
            amount:100,
            calories:45,
            protein:1,
            carbs:11,
            fat:0
        },
        {
            name:"Cabbage",
            type:"Vegetable",
            amount:100,
            calories:25,
            protein:1,
            carbs:5,
            fat:0
        },
        {
            name:"Carrot",
            type:"Vegetable",
            amount:100,
            calories:41,
            protein:0,
            carbs:9,
            fat:0
        },
        {
            name:"Cauliflower",
            type:"Vegetable",
            amount:100,
            calories:25,
            protein:1,
            carbs:4,
            fat:0
        },
        {
            name:"Celery",
            type:"Vegetable",
            amount:100,
            calories:16,
            protein:0,
            carbs:2,
            fat:0
        },
        {
            name:"Chick Pea",
            type:"Vegetable",
            amount:100,
            calories:180,
            protein:10,
            carbs:30,
            fat:3
        },
        {
            name:"Chives",
            type:"Vegetable",
            amount:100,
            calories:30,
            protein:3,
            carbs:4,
            fat:0
        },
        {
            name:"Collard Greens",
            type:"Vegetable",
            amount:100,
            calories:32,
            protein:3,
            carbs:5,
            fat:0
        },
        {
            name:"Daikon",
            type:"Vegetable",
            amount:100,
            calories:18,
            protein:0,
            carbs:4,
            fat:0
        },
        {
            name:"Fava Bean",
            type:"Vegetable",
            amount:100,
            calories:71,
            protein:5,
            carbs:12,
            fat:0
        },
        {
            name:"Garbanzo Bean",
            type:"Vegetable",
            amount:100,
            calories:180,
            protein:10,
            carbs:30,
            fat:3
        },
        {
            name:"Garlic",
            type:"Vegetable",
            amount:100,
            calories:149,
            protein:6,
            carbs:33,
            fat:0
        },
        {
            name:"Ginger",
            type:"Vegetable",
            amount:100,
            calories:80,
            protein:1,
            carbs:17,
            fat:0
        },
        {
            name:"Green Beans",
            type:"Vegetable",
            amount:100,
            calories:31,
            protein:1,
            carbs:6,
            fat:0
        },
        {
            name:"Horseradish",
            type:"Vegetable",
            amount:100,
            calories:48,
            protein:1,
            carbs:11,
            fat:0
        },
        {
            name:"Kale",
            type:"Vegetable",
            amount:100,
            calories:49,
            protein:4,
            carbs:8,
            fat:0
        },
        {
            name:"Leek",
            type:"Vegetable",
            amount:100,
            calories:61,
            protein:1,
            carbs:14,
            fat:0
        },
        {
            name:"Lemongrass",
            type:"Vegetable",
            amount:100,
            calories:99,
            protein:1,
            carbs:25,
            fat:0
        },
        {
            name:"Lentil",
            type:"Vegetable",
            amount:100,
            calories:116,
            protein:9,
            carbs:20,
            fat:0
        },
        {
            name:"Lettuce",
            type:"Vegetable",
            amount:100,
            calories:13,
            protein:1,
            carbs:2,
            fat:0
        },
        {
            name:"Lima Bean",
            type:"Vegetable",
            amount:100,
            calories:79,
            protein:4,
            carbs:14,
            fat:0
        },
        {
            name:"Mung Bean Sprout",
            type:"Vegetable",
            amount:100,
            calories:30,
            protein:3,
            carbs:5,
            fat:0
        },
        {
            name:"Mushrooms",
            type:"Vegetable",
            amount:100,
            calories:35,
            protein:5,
            carbs:5,
            fat:0
        },
        {
            name:"Portobello Mushrooms",
            type:"Vegetable",
            amount:100,
            calories:17,
            protein:1,
            carbs:5,
            fat:0
        },
        {
            name:"Shiitake Mushrooms",
            type:"Vegetable",
            amount:100,
            calories:56,
            protein:3,
            carbs:10,
            fat:0
        },
        {
            name:"Mustard Greens",
            type:"Vegetable",
            amount:100,
            calories:27,
            protein:2,
            carbs:4,
            fat:0
        },
        {
            name:"Okra",
            type:"Vegetable",
            amount:100,
            calories:33,
            protein:1,
            carbs:7,
            fat:0
        },
        {
            name:"Onion",
            type:"Vegetable",
            amount:100,
            calories:40,
            protein:1,
            carbs:9,
            fat:0
        },
        {
            name:"Parsnip",
            type:"Vegetable",
            amount:100,
            calories:75,
            protein:1,
            carbs:17,
            fat:0
        },
        {
            name:"Peas",
            type:"Vegetable",
            amount:100,
            calories:58,
            protein:3,
            carbs:10,
            fat:0
        },
        {
            name:"Potato",
            type:"Vegetable",
            amount:100,
            calories:77,
            protein:2,
            carbs:17,
            fat:0
        },
        {
            name:"Pumpkin",
            type:"Vegetable",
            amount:100,
            calories:34,
            protein:1,
            carbs:8,
            fat:0
        },
        {
            name:"Radish",
            type:"Vegetable",
            amount:100,
            calories:16,
            protein:0,
            carbs:3,
            fat:0
        },
        {
            name:"Rutabaga",
            type:"Vegetable",
            amount:100,
            calories:37,
            protein:1,
            carbs:8,
            fat:0
        },
        {
            name:"Shallot",
            type:"Vegetable",
            amount:100,
            calories:72,
            protein:2,
            carbs:16,
            fat:0
        },
        {
            name:"Snap Pea",
            type:"Vegetable",
            amount:100,
            calories:42,
            protein:2,
            carbs:7,
            fat:0
        },
        {
            name:"Snow Pea",
            type:"Vegetable",
            amount:100,
            calories:42,
            protein:2,
            carbs:7,
            fat:0
        },
        {
            name:"Soybean",
            type:"Vegetable",
            amount:100,
            calories:122,
            protein:10,
            carbs:9,
            fat:5
        },
        {
            name:"Spinach",
            type:"Vegetable",
            amount:100,
            calories:23,
            protein:2,
            carbs:3,
            fat:0
        },
        {
            name:"Scallion",
            type:"Vegetable",
            amount:100,
            calories:32,
            protein:1,
            carbs:7,
            fat:0
        },
        {
            name:"Summer Squash",
            type:"Vegetable",
            amount:100,
            calories:16,
            protein:1,
            carbs:3,
            fat:0
        },
        {
            name:"Swede",
            type:"Vegetable",
            amount:100,
            calories:37,
            protein:1,
            carbs:8,
            fat:0
        },
        {
            name:"Sweet Potato",
            type:"Vegetable",
            amount:100,
            calories:86,
            protein:1,
            carbs:20,
            fat:0
        },
        {
            name:"Taro",
            type:"Vegetable",
            amount:100,
            calories:112,
            protein:1,
            carbs:26,
            fat:0
        },
        {
            name:"Tomatillo",
            type:"Vegetable",
            amount:100,
            calories:32,
            protein:0,
            carbs:5,
            fat:1
        },
        {
            name:"Tomato",
            type:"Vegetable",
            amount:100,
            calories:18,
            protein:0,
            carbs:3,
            fat:0
        },
        {
            name:"Turnip",
            type:"Vegetable",
            amount:100,
            calories:28,
            protein:0,
            carbs:6,
            fat:0
        },
        {
            name:"Wasabi",
            type:"Vegetable",
            amount:100,
            calories:109,
            protein:4,
            carbs:23,
            fat:0
        },
        {
            name:"Watercress",
            type:"Vegetable",
            amount:100,
            calories:11,
            protein:2,
            carbs:1,
            fat:0
        },
        {
            name:"Wheatgrass",
            type:"Vegetable",
            amount:100,
            calories:16,
            protein:1,
            carbs:3,
            fat:0
        },
        {
            name:"Winter Squash",
            type:"Vegetable",
            amount:100,
            calories:34,
            protein:0,
            carbs:8,
            fat:0
        },
        {
            name:"Yam",
            type:"Vegetable",
            amount:100,
            calories:118,
            protein:1,
            carbs:27,
            fat:0
        },
        {
            name:"Yuca Root",
            type:"Vegetable",
            amount:100,
            calories:160,
            protein:1,
            carbs:38,
            fat:0
        },
        {
            name:"Zucchini",
            type:"Vegetable",
            amount:100,
            calories:21,
            protein:2,
            carbs:3,
            fat:0
        },
        {
            name:"Barley",
            type:"Grain",
            amount:100,
            calories:122,
            protein:2,
            carbs:28,
            fat:1
        },
        {
            name:"Brown Rice",
            type:"Grain",
            amount:100,
            calories:110,
            protein:3,
            carbs:23,
            fat:1
        },
        {
            name:"Bulgur",
            type:"Grain",
            amount:100,
            calories:83,
            protein:4,
            carbs:19,
            fat:0
        },
        {
            name:"Corn",
            type:"Grain",
            amount:100,
            calories:124,
            protein:3,
            carbs:24,
            fat:3
        },
        {
            name:"Cream of Rice",
            type:"Grain",
            amount:100,
            calories:127,
            protein:2,
            carbs:28,
            fat:0
        },
        {
            name:"Cream of Wheat",
            type:"Grain",
            amount:100,
            calories:112,
            protein:4,
            carbs:23,
            fat:0
        },
        {
            name:"Farro",
            type:"Grain",
            amount:100,
            calories:127,
            protein:5,
            carbs:26,
            fat:0
        },
        {
            name:"Grits",
            type:"Grain",
            amount:100,
            calories:111,
            protein:3,
            carbs:24,
            fat:0
        },
        {
            name:"Oats",
            type:"Grain",
            amount:100,
            calories:62,
            protein:3,
            carbs:11,
            fat:1
        },
        {
            name:"Quinoa",
            type:"Grain",
            amount:100,
            calories:143,
            protein:5,
            carbs:26,
            fat:2
        },
        {
            name:"Rice",
            type:"Grain",
            amount:100,
            calories:129,
            protein:3,
            carbs:28,
            fat:0
        },
        {
            name:"Ground Beef 80/20",
            type:"Meat",
            amount:100,
            calories:260,
            protein:26,
            carbs:0,
            fat:17
        },
        {
            name:"Ground Beef 85/15",
            type:"Meat",
            amount:100,
            calories:244,
            protein:26,
            carbs:0,
            fat:15
        },
        {
            name:"Ground Beef 90/10",
            type:"Meat",
            amount:100,
            calories:216,
            protein:27,
            carbs:0,
            fat:11
        },
        {
            name:"Ground Beef 95/5",
            type:"Meat",
            amount:100,
            calories:176,
            protein:27,
            carbs:0,
            fat:7
        },
        {
            name:"Beef Sirloin",
            type:"Meat",
            amount:100,
            calories:206,
            protein:26,
            carbs:0,
            fat:11
        },
        {
            name:"Beef Tenderloin",
            type:"Meat",
            amount:100,
            calories:202,
            protein:24,
            carbs:0,
            fat:12
        },
        {
            name:"Beef Ribeye",
            type:"Meat",
            amount:100,
            calories:253,
            protein:18,
            carbs:0,
            fat:19
        },
        {
            name:"Beef New York Strip",
            type:"Meat",
            amount:100,
            calories:225,
            protein:20,
            carbs:0,
            fat:14
        },
        {
            name:"Chicken Breast",
            type:"Meat",
            amount:100,
            calories:165,
            protein:31,
            carbs:0,
            fat:3
        },
        {
            name:"Chicken Thigh Skinless",
            type:"Meat",
            amount:100,
            calories:207,
            protein:26,
            carbs:0,
            fat:11
        },
        {
            name:"Chicken Leg Skinless",
            type:"Meat",
            amount:100,
            calories:189,
            protein:27,
            carbs:0,
            fat:8
        },
        {
            name:"Turkey Breast",
            type:"Meat",
            amount:100,
            calories:135,
            protein:30,
            carbs:0,
            fat:1
        },
        {
            name:"Pork Tenderloin",
            type:"Meat",
            amount:100,
            calories:171,
            protein:25,
            carbs:0,
            fat:7
        },
        {
            name:"Lean Ham",
            type:"Meat",
            amount:100,
            calories:110,
            protein:17,
            carbs:0,
            fat:3
        },
        {
            name:"Catfish",
            type:"Fish",
            amount:100,
            calories:144,
            protein:18,
            carbs:0,
            fat:7
        },
        {
            name:"Carp",
            type:"Fish",
            amount:100,
            calories:162,
            protein:22,
            carbs:0,
            fat:7
        },
        {
            name:"Cod",
            type:"Fish",
            amount:100,
            calories:105,
            protein:22,
            carbs:0,
            fat:0
        },
        {
            name:"Halibut",
            type:"Fish",
            amount:100,
            calories:111,
            protein:22,
            carbs:0,
            fat:1
        },
        {
            name:"Monkfish",
            type:"Fish",
            amount:100,
            calories:97,
            protein:18,
            carbs:0,
            fat:1
        },
        {
            name:"Oysters Canned",
            type:"Fish",
            amount:100,
            calories:68,
            protein:7,
            carbs:3,
            fat:2
        },
        {
            name:"Salmon",
            type:"Fish",
            amount:100,
            calories:139,
            protein:24,
            carbs:0,
            fat:4
        },
        {
            name:"Sea Bass",
            type:"Fish",
            amount:100,
            calories:152,
            protein:23,
            carbs:0,
            fat:6
        },
        {
            name:"Shrimp",
            type:"Fish",
            amount:100,
            calories:138,
            protein:27,
            carbs:1,
            fat:2
        },
        {
            name:"Snapper",
            type:"Fish",
            amount:100,
            calories:128,
            protein:26,
            carbs:0,
            fat:1
        },
        {
            name:"Tilapia",
            type:"Fish",
            amount:100,
            calories:125,
            protein:17,
            carbs:0,
            fat:5
        },
        {
            name:"Trout",
            type:"Fish",
            amount:100,
            calories:150,
            protein:19,
            carbs:0,
            fat:7
        },
        {
            name:"Tuna",
            type:"Fish",
            amount:100,
            calories:165,
            protein:22,
            carbs:0,
            fat:7
        },
        {
            name:"Almond",
            type:"Nuts",
            amount:100,
            calories:579,
            protein:21,
            carbs:21,
            fat:49
        },
        {
            name:"Brazil Nut",
            type:"Nuts",
            amount:100,
            calories:659,
            protein:14,
            carbs:11,
            fat:67
        },
        {
            name:"Cashew",
            type:"Nuts",
            amount:100,
            calories:553,
            protein:18,
            carbs:30,
            fat:43
        },
        {
            name:"Hazelnut",
            type:"Nuts",
            amount:100,
            calories:628,
            protein:14,
            carbs:16,
            fat:60
        },
        {
            name:"Macadamia Nut",
            type:"Nuts",
            amount:100,
            calories:718,
            protein:7,
            carbs:13,
            fat:76
        },
        {
            name:"Peanuts",
            type:"Nuts",
            amount:100,
            calories:567,
            protein:25,
            carbs:16,
            fat:49
        },
        {
            name:"Pecan",
            type:"Nuts",
            amount:100,
            calories:691,
            protein:9,
            carbs:13,
            fat:71
        },
        {
            name:"Pistachio",
            type:"Nuts",
            amount:100,
            calories:562,
            protein:20,
            carbs:27,
            fat:45
        },
        {
            name:"Walnut",
            type:"Nuts",
            amount:100,
            calories:654,
            protein:15,
            carbs:13,
            fat:65
        }
    ]

export default Food;